version: '3.1'

services:
  db:
    image: postgres
    restart: always
    container_name: my-postgres
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
      POSTGRES_DB: vocabulary
    volumes:
      - database-data:/var/lib/postgresql/data/
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  database-data:
