services:
  nginx:
    image: nginx:1.13
    volumes:
      - ./client/build:/usr/share/nginx/html
    ports:
      - 8080:80
    depends_on:
      - app

  app:
    image: node
    command: sh -c "npm install && npm run dev"
    ports:
      - 7000:7000
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: vocabulary

  db:
    image: postgres
    ports:
      - 5433:5432
    volumes:
      - database-data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: vocabulary
volumes:
  database-data: